pages = [{"l":"index.html","n":"t2","t":"t2","d":"","k":"static"},
{"l":"t2.html","n":"t2","t":"package t2","d":"t2","k":"package"},
{"l":"t2/Table.html","n":"Table","t":"trait Table","d":"t2/Table","k":"trait"},
{"l":"t2/Table.html","n":"apply","t":"def apply(row: Int, column: Int): String","d":"t2/Table","k":"def"},
{"l":"t2/Table.html","n":"column","t":"def column(index: Int): Seq[String]","d":"t2/Table","k":"def"},
{"l":"t2/Table.html","n":"columnCount","t":"def columnCount: Int","d":"t2/Table","k":"def"},
{"l":"t2/Table.html","n":"columns","t":"def columns: Seq[Seq[String]]","d":"t2/Table","k":"def"},
{"l":"t2/Table.html","n":"row","t":"def row(index: Int): Seq[String]","d":"t2/Table","k":"def"},
{"l":"t2/Table.html","n":"rowCount","t":"def rowCount: Int","d":"t2/Table","k":"def"},
{"l":"t2/Table.html","n":"rows","t":"def rows: Seq[Seq[String]]","d":"t2/Table","k":"def"},
{"l":"t2/Table$.html","n":"Table","t":"object Table","d":"t2/Table$","k":"object"},
{"l":"t2/Table$.html","n":"apply","t":"def apply(data: Seq[Seq[String]], rowOriented: Boolean): Table","d":"t2/Table$","k":"def"},
{"l":"t2/Table$.html","n":"forColumns","t":"def forColumns(data: Seq[Seq[String]]): Table","d":"t2/Table$","k":"def"},
{"l":"t2/Table$.html","n":"forRows","t":"def forRows(data: Seq[Seq[String]]): Table","d":"t2/Table$","k":"def"},
{"l":"t2/TableBuilder.html","n":"TableBuilder","t":"trait TableBuilder","d":"t2/TableBuilder","k":"trait"},
{"l":"t2/TableBuilder.html","n":"add","t":"def add(values: Seq[String]): TableBuilder","d":"t2/TableBuilder","k":"def"},
{"l":"t2/TableBuilder.html","n":"add","t":"def add(one: String, more: String*): TableBuilder","d":"t2/TableBuilder","k":"def"},
{"l":"t2/TableBuilder.html","n":"addAll","t":"def addAll(values: Seq[Seq[String]]): TableBuilder","d":"t2/TableBuilder","k":"def"},
{"l":"t2/TableBuilder.html","n":"addAll","t":"def addAll(one: Seq[String], more: Seq[String]*): TableBuilder","d":"t2/TableBuilder","k":"def"},
{"l":"t2/TableBuilder.html","n":"build","t":"def build(): Table","d":"t2/TableBuilder","k":"def"},
{"l":"t2/TableBuilder.html","n":"columnCount","t":"def columnCount: Int","d":"t2/TableBuilder","k":"def"},
{"l":"t2/TableBuilder.html","n":"isRowOriented","t":"def isRowOriented: Boolean","d":"t2/TableBuilder","k":"def"},
{"l":"t2/TableBuilder.html","n":"reset","t":"def reset(): TableBuilder","d":"t2/TableBuilder","k":"def"},
{"l":"t2/TableBuilder.html","n":"rowCount","t":"def rowCount: Int","d":"t2/TableBuilder","k":"def"},
{"l":"t2/TableBuilder$.html","n":"TableBuilder","t":"object TableBuilder","d":"t2/TableBuilder$","k":"object"},
{"l":"t2/TableBuilder$.html","n":"apply","t":"def apply(rowOriented: Boolean): TableBuilder","d":"t2/TableBuilder$","k":"def"},
{"l":"t2/TableBuilder$.html","n":"forColumns","t":"def forColumns: TableBuilder","d":"t2/TableBuilder$","k":"def"},
{"l":"t2/TableBuilder$.html","n":"forRows","t":"def forRows: TableBuilder","d":"t2/TableBuilder$","k":"def"},
{"l":"t2/TableWriter.html","n":"TableWriter","t":"trait TableWriter","d":"t2/TableWriter","k":"trait"},
{"l":"t2/TableWriter.html","n":"write","t":"def write(out: Writer, table: Table): Unit","d":"t2/TableWriter","k":"def"},
{"l":"t2/TableWriter.html","n":"write","t":"def write(out: OutputStream, table: Table): Unit","d":"t2/TableWriter","k":"def"},
{"l":"t2/TableWriter$.html","n":"TableWriter","t":"object TableWriter","d":"t2/TableWriter$","k":"object"},
{"l":"t2/TableWriter$.html","n":"apply","t":"def apply(config: (String, String)*): TableWriter","d":"t2/TableWriter$","k":"def"},
{"l":"t2/TableWriter$.html","n":"apply","t":"def apply(config: Map[String, String]): TableWriter","d":"t2/TableWriter$","k":"def"},
{"l":"docs/index.html","n":"t2","t":"t2","d":"","k":"static"}];